version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: concrete-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: concretecms
      MYSQL_USER: concrete
      MYSQL_PASSWORD: concretepass
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: concrete-app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      # These match the DB service above
      DB_HOST: db
      DB_NAME: concretecms
      DB_USER: concrete
      DB_PASSWORD: concretepass

volumes:
  db_data:
