name: Build & Push Docker Image

on:
  push:
    branches:
      - main   # Run only when code is pushed/merged into main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # Needed for GHCR

    steps:
      # Step 1: Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract repository owner and name (in lowercase)
      - name: Set IMAGE_NAME
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/concrete-cms"
          echo "IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} .

      # Step 5: Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
