name: Build & Push Docker Image

on:
  push:
    branches:
      - main   # Run only when code is pushed/merged into main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # Required for GHCR push

    steps:
      # Step 1: Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fix Git "dubious ownership" issue
      - name: Configure Git safe directory
        run: git config --global --add safe.directory /var/www/html

      # Step 3: Log in to GitHub Container Registry (GHCR) using PAT
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 4: Set Docker image name
      - name: Set IMAGE_NAME
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/concrete-cms"
          echo "IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} .

      # Step 6: Push Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
