name: Build & Push Docker Image

on:
  push:
    branches:
      - main   # Change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout your repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/concrete-cms
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/concrete-cms
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

